Helga fix (#52)
this should have been just the c2b915b. great, my `develop` branch diverted from the one i'm "working" on for the past year... anyways, it's jsut so that #51 gets an update of what's been tried so far, and apparently not doing anything. his fix might be better than this.

the fix was about the fact that vanilla `FireAll.fire` takes in various arguments, and the `memoryMap` must not be null for it, however due to it being java it does not enforce nullability and crashes. the new `FireAllKotlin` enforces nullability on it properly

UPDATE:
in fact... writing out this comment made me realize something. That i didn't put in any safety at all if I didn't cater to the parameter's needs and would just mask the issue by having it throwing NPEs on my "safe" FireAllKotlin calls rather than the real underlying issue. I would be just changing the symptom.

So the "safety" was kinda thrown out the window and reworked completely in commit d663535 - so that each of the 'safe' methods accept a nullable `memoryMap` parameter and then figuring out what to do with it.

So now, this new `FireAllKotlin` is **actually** safe to be used directly with code coming from java, with a case similar to this:
```
FireAllKotlin.fire(null, dialog, dialog.plugin.memoryMap, "SomeParams")
```

and **that's** an actual improvement over introducing nullability on *my* version of `memoryMap` variable/parameter
--------------


* Fix SVC issue where it crashes on dialogPlugin.memoryMap

This attempts to solve the following stacktrace:

102366     2557126 [Thread-2] INFO sound.O Cleaning up music with id [voidling_exploration_theme.ogg]
102369     2558568 [Thread-2] ERROR com.fs.starfarer.combat.CombatMain java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "memoryMap" is null
102370     java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "memoryMap" is null
102371             at com.fs.starfarer.api.impl.campaign.rulecmd.BaseCommandPlugin.getEntityMemory(BaseCommandPlugin.java:21)
102372             at com.fs.starfarer.api.impl.campaign.rulecmd.FireAll.execute(FireAll.java:73)
102373             at com.fs.starfarer.api.impl.campaign.rulecmd.FireAll.fire(FireAll.java:56)
102374             at exoticatechnologies.campaign.listeners.CampaignEventListener.reportShownInteractionDialog(CampaignEventListener.kt:88)
102375             at com.fs.starfarer.campaign.CampaignEngine.reportShowInteractionDialog(Unknown Source)
102376             at com.fs.starfarer.campaign.CampaignState.startEncounterInvolvingPlayerFleet(Unknown Source)
102377             at com.fs.starfarer.campaign.BaseLocation.advance(Unknown Source)
102378             at com.fs.starfarer.campaign.Hyperspace.advance(Unknown Source)
102379             at com.fs.starfarer.campaign.CampaignEngine.advance(Unknown Source)
102380             at com.fs.starfarer.campaign.CampaignState.advance(Unknown Source)
102381             at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
102382             at com.fs.state.AppDriver.begin(Unknown Source)
102383             at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
102384             at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
102385             at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
102386             at java.base/java.lang.Thread.run(Unknown Source)

however, I have no idea whether it succeeds or not.
PR #51 supposedly does this alot better.

* Revert CampaignEventListener to 'develop' branch version - it did not fix anything

* Proper fix for helga's memoryMap problem

Thing is, the dialog.plugin.memoryMap is nullable and is not always present.
So, treat it as a nullable map instead of always presuming it's non-null.

This should resolve the following crash stacktrace:
```
8725666 [Thread-2] ERROR com.fs.starfarer.combat.CombatMain java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "memoryMap" is null
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "memoryMap" is null
        at com.fs.starfarer.api.impl.campaign.rulecmd.BaseCommandPlugin.getEntityMemory(BaseCommandPlugin.java:21)
        at com.fs.starfarer.api.impl.campaign.rulecmd.FireAll.execute(FireAll.java:73)
        at com.fs.starfarer.api.impl.campaign.rulecmd.FireAll.fire(FireAll.java:56)
        at exoticatechnologies.campaign.listeners.CampaignEventListener.reportShownInteractionDialog(CampaignEventListener.kt:88)
        at com.fs.starfarer.campaign.CampaignEngine.reportShowInteractionDialog(Unknown Source)
        at com.fs.starfarer.campaign.CampaignState.showInteractionDialog(Unknown Source)
        at tecrys.svc.world.notifications.NotificationBase.showNotification(NotificationBase.kt:20)
        at tecrys.svc.world.notifications.NotificationBase.showIfRequested(NotificationBase.kt:27)
        at tecrys.svc.world.notifications.NotificationShower.advance(NotificationShower.kt:61)
```

* Improve the fix - make a kotlin-safe wrapper around FireAll.fire(...)

The improvement is that it no longer accepts nullable arguments for non-nullable parameters.
So there's that.

* Abandon the safe fireAll() method in favor of FireAllKotlin

The FireAllKotlin is the new object that inherits FireAll, and it's static
fire method calls into the new fire_safe extension method, which then calls
into the old FireAll.fire() static method.

This is done this way because I cannot make static extension methods on java objects.
*BUT* - I can do it this way, and since every FireAll.fire() invocation essentially creates
a new FireAll instance to call it on, having one extra instance with my object should be fine.

I think.

This is essentially the old `fireAll()` method generalized a bit more so it can be reused from
other places too.

* Minor touchups, helga validated everything still works.

Thats it, ship it.

* Actually throw out the 'safety' through the window after thinking for a bit ...

The whole "safety" bit applies when using it from my own Kotlin code.
However, if I dare to pass `dialog.plugin.memoryMap` it not only bypasses the whole
new 'safety' i put in, but it will also crash with a NPE on my method invocation rather
than the actual problem.

So, i've overengineered some nonsense that will crash when just used directly with starsector
API code, rather than done tediously. In fact, the first implementation was better than what I had.

Anyways, before i go on a rant - all methods now properly return their boolean return values.
The safety has been replaced so that the memoryMap is a nullable parameter everywhere.
Each of the methods will nullcheck the memory map and act accordingly.

Somehow I feel like this 'improvement' is a step back since I will not be refactoring the
CampaignEventListener to use the new capabilities, but so be it.

EDIT:
added some javadoc.
To help my future self understand why this change happened -
This code works great if used in a case like this:
```
val memoryMap = getMemoryMap(dialog.plugin)	// returns a nullable map
if (memoryMap != null ) {
   . . .
   FireAllKotlin.fire( /* 4 parameter call */ )
} else {
   // whatever
}
```

But when it's used like this:
```
FireAllKotlin.fire(<whatever>, dialog, dialog.plugin.memoryMap, <whatever>)
```
it literally bypasses all this compile-time safety due to it coming from Java land.
And instead of breaking on the original point:
```
com.fs.starfarer.api.impl.campaign.rulecmd.BaseCommandPlugin.getEntityMemory(BaseCommandPlugin.java:21)
```
It will instead break with a NPE on `FireAllKotlin.fire(...)` invocation due to parameter being non-nullable.

So to allow this usage ergonomics, the whole safety mechanism had to be reworked so that this class is actually
more inter-usable with java code.

Now all methods will double-check everything and behave properly, and still be safe. With just alot more work
than the original
```
val memoryMap = getMemoryMap(...)
if (memoryMap != null ) {
   FireAll.fire(...)
} else {
    log("memoryMap was null)
}
```

*sigh*

* Decided to move the getMemoryMap to FireAllKotlin as well and make it more utility

* Address own CR comments