Ammo creator system (#15)
AmmoCraftingSystem Exotica
---------------------------------- 

As mentioned in issue #11 - the second of the two systems is the cheap cheaty ammo creator system.

So, in order to make it less cheaty, it also has a 30% chance of failing.

tl;dr is - it's a system that auto-calculates how long it will run, depending on how good/bad the numbers come out (thanks to corrupted, pristine and other variations of Exoticas) to refill ammo to 100%, by simply calculating how many periods it needs to run for, then multiplying that number by the period duration.

Once the duration has been calculated (and the system has been activated of course), it will roll a die and either display a failure text, failure afterimage, play a failure sound, and if fail damage is turned on - it will also play an explosion on the ship and damage it for something between 10 and 100 damage (also affected by the `getPositiveMult` and `getNegativeMult` modifiers).

By default, it should recharge 10% ammo every 10 seconds.

In reality, after every period runs out, a die will be rolled. If the die indicates a failure (<= 30), failure graphics will be shown, a failure text will be displayed, a failure afterimage will blip, and a failure sound will be played along with damaging the ship for 10-100 damage (also affected by positive/negative multipliers) and visually displaying an explosion on the ship.
If the dice shows a success, then all affected weapons will be reloaded for 10%, a success afterimage will blip and a successful sound will be played.

Also, a new ConditionOperator was made, "ammoWeapons" that can count how many weapons are using ammo, so that filtering condition can be used in exotics.json


Commit messages:


* Initial implementation of the AmmoCraftingSystem

* Add graphics for the system icon and it's item image

* Utility class for holding Exotic-related stuff

Apparently very useful for those getPositiveMult(...) and getNegativeMult(...) calls.

* Update special_items.csv with the new item for ammocreator

* Add new Condition to use inside exotics.json to enumerate ammo-using weapons

A new condition had to be made, since i want the new ammo creating system to be applicable
to only ships that have >= 2 ammo-using weapons.

So the condition can be referenced inside exotics.json as "ammoWeapons"

example:
{"id": "ammoWeapons", "operator": ">=", "expected": 2, "cannotApplyReason": "The ship must have more than two ammo-based weapons.", "weight": 0.5, "maxWeight": 3}

* Update exotics.json to mention AmmoCraftingSystem and use new condition

* Let AmmoCraftingSystem be available for randomly spawning in fleets

* New string for AmmoCraftingSystem and tie in with it's modifyTooltip() call

Ok, now that a string is in place, and all replacements are done in the modifyTooltip() call,
we can start getting rid of useless stuf... like this StuffHolder for one. Seemed like a decent idea.
Turned out it most likely wasn't and was just a rushed 'abstraction' :/

* Get rid of exoticStuffHolder member, it's uses and relevant methods

Unfortunatelly this produced a small usage wart of reloadWeapon() having to be
extended with more arguments, but on the other hand - why not.

The class will survive for now, because it just *might* become useful for edge-cases
where we need to do something with those three things without having access to them.

But for now, it's nuked out of the system that brought it to existence :D

* Latest JAR with the AmmoCreator

* Add playing of sounds to AmmoCraftingSystem, some necessary refactoring and new JAR

Well, considering that RewindSystem had a playSound() method of it's own, it'd be kinda dumb
to just copypaste it and not reuse it. So it got moved to a KtxUtils file in the utils package.

So, RewindSystem was affected by that move, and had to be adjusted to use the new version of the method.
And AmmoCraftingSystem just added usages of the playSound() method from the KtxUtils as well.

Also added the 3 new sounds, and updated the sounds.json

EDIT: now i've added the sounds.json modifications but also - the new JAR as well

* Fix a bug before it actually happens and I fail to catch it :)

Namely, as I was writing out the PR description, and I came to the part that says
"by default, period lasts 10 seconds (affected by positive/negative multipliers)"
i remembered that I hardcoded the IntervalUtil to last 9.95,10.05 seconds.

In other words, if somehow the period got to last 5 seconds, this thing would
only tick every 10 seconds (2 periods), so I had to fix that.

While at it, another issue was taken care of - namely the tooltip duration was only
using the period duration instead of the whole (dynamic) system activation duration.

That one is also taken care of.

Finally, the new JAR is also put in.

* Fix new condition issue and rename it while at it

aka "pay the price for your naivety". Somehow I naively thought
that just making a new class is going to make it all work out magically.

Without registering the new class anywhere, or instantiating a new instance
or anything.

Well, the following crash proved me otherwise:
java.lang.NullPointerException: Condition for ammoWeapons is missing.
	at exoticatechnologies.modifications.conditions.ConditionDict$Companion.getCondFromDict(ConditionDict.kt:70)
	at exoticatechnologies.modifications.conditions.ConditionDict$Companion.getCondFromJSONObject(ConditionDict.kt:50)
	at exoticatechnologies.modifications.conditions.ConditionDict$Companion.getCondsFromJSONArray(ConditionDict.kt:43)
	at exoticatechnologies.modifications.Modification.<init>(Modification.kt:40)
	at exoticatechnologies.modifications.exotics.Exotic.<init>(Exotic.kt:28)
	at exoticatechnologies.modifications.exotics.impl.AmmoCraftingSystem.<init>(AmmoCraftingSystem.kt:30)
	at exoticatechnologies.modifications.exotics.ExoticsHandler.populateExotics(ExoticsHandler.kt:59)
	at exoticatechnologies.modifications.exotics.ExoticsHandler.initialize(ExoticsHandler.kt:36)
	at exoticatechnologies.ETModPlugin.onApplicationLoad(ETModPlugin.java:59)
	at com.fs.starfarer.loading.ResourceLoaderState.init(Unknown Source)

So, lets just register the AmmoWeapons in this ConditionDict.
But also, while creating the PR i got an idea about leaving a comment to rename it to
AmmoUsingWeapons instead, as that much better conveys both it's purpose and what it does.

Also changed it's usage to "ammoUsingWeapons".

EDIT: also added a new JAR while at it.

So I renamed it, updated the exotics.json, and it's ready for another round of testing after a new deployment.

* Fix a whoopsie and also fix the image too

Turns out, somehow I didn't add an entry for the AmmoCraftingSystem in
the settings.json. Alright, so I added it.

But while at it, I also removed the background from the old ammocreator (?)
image, and named it properly - ammocraftingsystem.png to be inline with other
images named exactly like their systems are.

* Fix strings.json wording and highlighting

* Made a new ReloadableAmmoUsingWeapons condition

Well, maybe the previous condition was too lax, compared what the actual system
will do in-game. So, let's consolidate them to actually check for similar things.

The new ReloadableAmmoUsingWeapons will also make sure the WeaponSpecAPI doesn't have
the NO_RELOAD tag, just like the AmmoCraftingSystem's AmmoCreator will do too.

Though, for some reason, doesn't seem to work good on missiles?

* Fix rolling dice - allow only rolls between 0 and 99

Wouldn't have changed it otherwise but there's two reasons.

1) these logs worry me

[AmmoCraftingSystem] Period has passed, rolled chance for reloading	rolledChance: -89
[AmmoCraftingSystem] Period has passed, rolled chance for reloading	rolledChance: 67
[AmmoCraftingSystem] Period has passed, rolled chance for reloading	rolledChance: -88
[AmmoCraftingSystem] Period has passed, rolled chance for reloading	rolledChance: -42
[AmmoCraftingSystem] Period has passed, rolled chance for reloading	rolledChance: -91
[AmmoCraftingSystem] Period has passed, rolled chance for reloading	rolledChance: -52
[AmmoCraftingSystem] Period has passed, rolled chance for reloading	rolledChance: -40

2) the logic we use for checking for success is this:

if (rolledChance < getFailChance(member, mods, exoticData)) {

regardless of what the fail chance ends up being, a negative number is always less than any positive non-zero number.

So, this needs to be fixed.

* Fix explosion size

The explosion size, while small, is effective. Needs to be bigger. It's location also needs to be
randomized thru the ship a bit, but that can be taken care of later. There are bigger problems to fix now.

* Fix reload amount and add more logs

Well... awkward. The "period reload amount" should be a number between 0 and 1.
Which then gets multiplied by maxAmmo and we should end up refilling around 10% of ammo.

Well, this seems to have been refilling 10x maxAmmo instead, because there was no division by 100.
It just took the "percent" value at face value.

* Refix the rolledChance again

To make it distribute random numbers in a [0,99] range, we need to add +1
to the 'until' part of the range, because in the random.nextInt(from,until)
the 'from' is inclusive but the 'until' is exclusive. So it does need to
be random.nextInt(0,100) and I reduced it to avoid rolling 101 number instead.

* Make failed reload text bigger

* Add saving/restoring of weapons' original reload data values

Well, aside from the problem of the weapons' reloading 10x their maxAmmo,
another problem was that even when the system shut down and deactivated,
they never stopped reloading ammo.

This is most likely due to the fact that the ammoTracker's values were never
restored to their original values, so they kept their "10% every 10 sec" rate.

Fix that by creating a map of original values when the system activates,
and restoring each weapon.ammoTracker's values to the saved values in the map.

This should avoid overwriting due to the fact that we use WeaponAPI instances rather
than their IDs but... hopefully nothing breaks.

EDIT: also add latest JAR

* Fix problem with broken tooltips ...

These recent fixes, while most likely have fixed plenty of issues,
have also broken the tooltip one - the one probably guilty for why
the issues were put in the code in the first place.

tl;dr - "Adds a system, which when activated, regenerates 0% of every ammo
using weapon every 10 seconds for 10000 seconds".

So, changing the getPeriodReloadAmount from a whole number (30) to a decimal number
(0.3) has messed up the scale completely.

Fixed by introducing a new getPeriodReloadAmountPercentage that returns a whole number
like before. So the problematic usages were replaced with calls to the new method.

* Fix the explosion again - it was too yellow and small

* Try to fix reloading again...

Well, the swarm missile always seems to reload to the max regardless of how empty it was
before the system is activated.

Either the resetAmmo() call is messing it up, or the ammoPerSecond not being scaled
by the duration makes it instantly fill up instead of doing it gradually.

* Leave a big rant for tomorrow-me to read and fix, this reload idea was garbage

Fuck you hacked missile forge and your "seemingly sound idea" when all the work
is actually done by just the resetAmmo() call....

* Completely reworked the reloadWeapon() function

Instead of messing around by vanilla "ammo over time" capabilities,
why don't I just add ammo when I should and do nothing when I should not.

This gives much more control over both:
- how much ammo is added per period
- whether or not ammo is added during a period

After testing, it works much better than the previous version and also doesn't
completely fill up the weapon in first period like the previous one. Also no
refilling surviving either.

I should get rid of ReloadData or what was it's name...

* Get rid of ReloadData map and add the latest JAR too

* Randomize visual explosion location

Instad of it always being dead-center in the middle of the ship, how about using an alternative
idea and just randomizing it a bit somewhere around the ship.

which gives me an even better idea...

* Consolidate random location on ship

Based on an idea in the previous commit, we now calculate the random position
on the ship, and use it not just for the visual explosion, but the applyDamage()
and addFloatingText() calls too.

* 'Fix' the explosion location randomness

So, as it turns out, segments don't really return an absolute location,
but rather just a relative location. However, when we do something like

    Vector2f(
        shipLocation.x + segmentLocation.x,
        shipLocation.y + segmentLocation.y
    )

It worked great for large ships, but worked like crap for the small ship i'm
testing with. With the small ship, the explosion is literally on the edge of
if the ship, or it's corner or something like that.

So, what I think needs to be done is, to get a random (X,Y) in segment's (x/2,y/2)
and go from -that to +that and add that to ship's location. That might work out better.

* Try to fix segment random - try1

* Try to fix segment random - try2

It's still going out of (ship) bounds sometimes for both large and small ships.
Something is going wrong here.

* Re-formatted code (and added debug info in last commit) and the game runs slow like shit now :/

* Perhaps it was a bad build; the game runs normally again but the segment location part seems busted

* Attempy to fix segment randomness - try3

Alright, so I see a problem.

[AmmoCraftingSystem] --> generateRandomLocationOnShip()	shipLocation: Vector2f[204.9541, -1535.2051]
[AmmoCraftingSystem] generateRandomLocationOnShip()	segmentLocation: Vector2f[-48.907772, -1629.393]
[AmmoCraftingSystem] generateRandomLocationOnShip()	segment location != ship location
[AmmoCraftingSystem] generateRandomLocationOnShip()	segmentX: -24.453886, segmentY: -814.6965
[AmmoCraftingSystem] generateRandomLocationOnShip()	randX: 98.74124, randY: -816.4
[AmmoCraftingSystem] <-- generateRandomLocationOnShip()	retVal: Vector2f[98.74124, -816.4]

ok, so it seems like i'm still using segmentX/2 thinking that segment.location is relative instead of absolute....
which is obviously wrong.

So, the randomness that *needs* to be done, if any is to be done, is between
shipLocation.x and shipLocation.x + diffX
where diffX = abs(shiplocation.y) - abs(segmentLocation.y)

or abs(segment) - abs(shipLocation), whatever. segments left of the center will produce negative diff, segments
right of the center will produce positive diffs, yet - it doesn't matter where we show the explosion.
we don't need to show it *exactly* on the random segment. we just want them to be within ship bounds and not
always be in the center.

So lets try that idea. But first - lets get rid of segmentX = segmentLocation.x / 2 since that introduces these huge jumps into emptiness.

* Attempt to fix segment randomness - try4

Ok, after getting rid of segment.x / 2 part it still falls outside of the small ship.
So, lets try with the diff approach. Or rather, 3/4 * diff just to be on the safe side.

* Attempt to fix segment randomness - try5

Ok, there's no way that some segment locations aren't relative, it just doesn't make sense.
When i test with the "oh pawlease" ship, some segments are 1000+ units away from the ship's location.
That's like more than half of the screen away. can't be true.

So, I either have math that works great for big ships and sucks for this one, or I have math that works good
for the small ship but somehow sucks for the big ship.

So now, I'm doing something different. if the diff > 1000 i "change my mind" and consider the location to be
relative, and recalibrate the diffX and diffY.

Lets see where that gets me so far...

* Fix segment randomness

Initial testing of 3 rounds on both large and small ship have proven successful
and it seems to finally work great for both.

Time for some cleanup, minor refactor and of course - stress-testing.

* Some cleanup and DEBUG stuff off, time for CR

Turned off the DEBUG flag, during testing I saw nothing bad.
Time for code-review and stress-testing this shit. I think it works fine.

* Stuff that might be useful later

* Add one more sound for ammo creator failure

* Added additional visual flair on failure

* Added flag for logging and also logging weapon names

* Fix the 'inverted' problem with segment randomness

Well, it turns out, the ship location isn't always at the center, and the whole
"it won't matter if i don't get the sign right" was a big problem when apparently
a segment from the top of the ship was selected and we went that far downwards.

So after the calculation was corrected, I thought the brokenness went away however...
I saw another repro just now, though not as bad as it used to be.

Lets keep this and call it done.

* Finally fix the segment problem of spawning explosions/visuals outside of the ship

Well, problem is finally solved for good. Instead of the dumb "switch to absolute positions if diff > 1000"
which didn't make sense to begin with becase:
1) the segment locations are always absolute
2) it's not always going to be 1000 and is most likely ship size dependant

instead of introducing a yet-another-codesmell with comparisons with ship width/height, lets just check if the
generated point is within bounds, and if it's not - generate a new one that is within bounds.

On the downside - this makes the explosions hit other modules less likely (read: impossible)
On the upside - we won't be having explosions outside of ship bounds, period.

The multi-module stuff will be taken care of eventually, in the multimodule themed PR.

* Address CR comments part1 - Get rid of ExoticStuffHolder

* Address CR comments part2 - ReloadableAmmoUsingWeapons logs

* Address CR comments part3 - KtxUtils::getAllShipWeapons logs

* Address CR comments part4 - shouldActivateAI patch

Rather than activating when we have at least one non-full weapon, we will now
activate only if we have at least one weapon below quarter of max ammo.

* Address CR comments part5 - remove commented-out block

* Address CR comments part6 - rewrite 'bad candidate' part of random ship location

* Address CR comments part7 - get rid of useless inline comments

* Consolidate KtxUtils into Extensions; new JAR

* Latest JAR

* Add few more logs to reloadWeapon; confirm there are no problems with reloading

* New 'bad' afterimage color

It's some sort of dark purple. It's not that great, looks like crap on the big ship
but hey - at least it's visible.

So i'll keep it until multimodule ships get fixed.

* Tweak fail damage parameters from 10-100 to 100-400

Changed the 10-100 to 100-400 which seemed very fine during testing.
It does leave some damage after 4-5 activations because the first activations
strip off armor, but in a real-world scenario where the ship is fighting - i guess
we'll just have to see what's there to see and fix later if it needs fixing.

* Latest JAR

* Address CR comments and new JAR