Adapt the scuttle interceptor a bit, however there is one big problem with javaassist
The problem being, the game is refusing to load the JAR because it's either using
`java.lang.reflect` or `java.file` things in it. So before I venture into using
MethodHandles to go around those problems, ByteBuddy or something else should be
evaluated to see how big of a deal would be to use that instead.

Relevant stacktrace:
```
140538 [Thread-3] ERROR exoticatechnologies.util.reflect.interceptors.FleetDataScuttleInterceptor  - Failed to setup scuttle interceptor: File access and reflection are not allowed to scripts.
java.lang.SecurityException: File access and reflection are not allowed to scripts.
	at com.fs.starfarer.loading.scripts.OoOO.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at javassist.ClassPool.<init>(ClassPool.java:192)
	at javassist.ClassPool.getDefault(ClassPool.java:228)
	at exoticatechnologies.util.reflect.interceptors.FleetDataScuttleInterceptor.setupInterceptor(FleetDataScuttleInterceptor.kt:17)
	at exoticatechnologies.ETModPlugin.onApplicationLoad(ETModPlugin.java:49)
	at com.fs.starfarer.loading.ResourceLoaderState.init(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.super(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```