Proper fix for helga's memoryMap problem
Thing is, the dialog.plugin.memoryMap is nullable and is not always present.
So, treat it as a nullable map instead of always presuming it's non-null.

This should resolve the following crash stacktrace:
```
8725666 [Thread-2] ERROR com.fs.starfarer.combat.CombatMain java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "memoryMap" is null
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "memoryMap" is null
        at com.fs.starfarer.api.impl.campaign.rulecmd.BaseCommandPlugin.getEntityMemory(BaseCommandPlugin.java:21)
        at com.fs.starfarer.api.impl.campaign.rulecmd.FireAll.execute(FireAll.java:73)
        at com.fs.starfarer.api.impl.campaign.rulecmd.FireAll.fire(FireAll.java:56)
        at exoticatechnologies.campaign.listeners.CampaignEventListener.reportShownInteractionDialog(CampaignEventListener.kt:88)
        at com.fs.starfarer.campaign.CampaignEngine.reportShowInteractionDialog(Unknown Source)
        at com.fs.starfarer.campaign.CampaignState.showInteractionDialog(Unknown Source)
        at tecrys.svc.world.notifications.NotificationBase.showNotification(NotificationBase.kt:20)
        at tecrys.svc.world.notifications.NotificationBase.showIfRequested(NotificationBase.kt:27)
        at tecrys.svc.world.notifications.NotificationShower.advance(NotificationShower.kt:61)
```