issue 35 - Initial commit of the javaassist integration
And so far, it seems like this version is being compiled with java8
```
java.lang.UnsupportedClassVersionError: javassist/ClassPool : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at exoticatechnologies.util.reflect.interceptors.FleetDataScuttleInterceptor.setupInterceptor(FleetDataScuttleInterceptor.kt:17)
	at exoticatechnologies.ETModPlugin.onApplicationLoad(ETModPlugin.java:49)
	at com.fs.starfarer.loading.ResourceLoaderState.init(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.super(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

So we need to find a version that supports java7.